export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const INCREASE_FOOD = 'INCREASE_FOOD'
export const DECREASE_FOOD = 'DECREASE_FOOD'
export const CLEAR_SELECT = 'CLEAR_SELECT'
export const SET_TOKEN = 'SET_TOKEN'

 